# Generated by Django 2.2.7 on 2019-12-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='appointment_allotted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('C', 'Coloring'), ('HC', 'Haircut'), ('HS', 'Hairstyle'), ('MU', 'Make Up'), ('M', 'Manicure'), ('D', 'Depilation'), ('P', 'Pedicure'), ('S', 'Spa')], default=None, max_length=1, null=True),
        ),
        migrations.RemoveField(
            model_name='service',
            name='master',
        ),
        migrations.AddField(
            model_name='service',
            name='master',
            field=models.ManyToManyField(blank=True, default=None, to='appl.Master'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('app_date', models.DateTimeField()),
                ('vacant', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Service')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.Appointment'),
        ),
    ]
